#+Title: DOOM EMACS config CAF
#+PROPERTY: header-args :eval no

* Theme

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+begin_src emacs-lisp
(setq doom-theme 'doom-tokyo-night)

(setq doom-font (font-spec :family "FiraMono Nerd Font" :size 18))
#+end_src

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.

#+begin_src emacs-lisp
(setq display-line-numbers-type `relative)
#+end_src

* Editor

#+begin_src emacs-lisp
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)
(setq tab-width 4)
(setq indent-line-function 'insert-tab)
(setq org-edit-src-content-indentation 0)
#+end_src

* Dired

#+begin_src emacs-lisp
(evil-define-key `normal dired-mode-map
  (kbd "h") `dired-up-directory
  (kbd "l") `dired-find-file
  )
#+end_src

* Org
** Org Roam

Main Directory for Roam Notes

#+begin_src emacs-lisp
(setq org-roam-directory "G:/Workstation/Notes/")
#+end_src

For Integrating subdirectories in the Roam main directory

#+begin_src emacs-lisp
(after! org-roam
  (setq org-roam-list-files-commands '(find fd fdfind rg)))
#+end_src

** Images

#+begin_src emacs-lisp
(after! org-block
  (setq org-image-actual-width 600))
#+end_src

** Lists

Modificar las bullets de una lista

#+begin_src emacs-lisp
(setq org-superstar-special-todo-items t)
(setq org-superstar-item-bullet-alist
  '((?* . ?✦)
    (?+ . ?◆)
    (?- . ?●)))
#+end_src

Modificar TODO Lists

#+begin_src emacs-lisp
(add-hook 'org-mode-hook
          (lambda ()
            (push '("[ ]" . "❎") prettify-symbols-alist)
            (push '("[X]" . "✅" ) prettify-symbols-alist)
            (prettify-symbols-mode)
            ))
#+end_src

** Emojis

Set the emoji style, Options:



#+begin_src emacs-lisp
(setq emojify-display-style 'unicode)
#+end_src

** Folding

Set Fold at startup

#+begin_src emacs-lisp
(after! org
  (setq org-startup-folded t))
#+end_src

For white spaces on folding

#+begin_src emacs-lisp :tangle no
(setq org-cycle-separator-lines 0)
#+end_src

** Emphasis

#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src

** Enable Docs Mode

#+begin_src emacs-lisp :tangle no
(add-hook! 'org-mode-hook 'doom-docs-mode)
#+end_src

** Headers

Headers size

#+begin_src emacs-lisp :tangle yes
(let* (
       (headline `(:weight bold)))

  (custom-theme-set-faces
   'user
   `(org-level-8 ((t (,@headline :inherit outline-8))))
   `(org-level-7 ((t (,@headline :inherit outline-7))))
   `(org-level-6 ((t (,@headline :inherit outline-6))))
   `(org-level-5 ((t (,@headline :inherit outline-5))))
   `(org-level-4 ((t (,@headline :inherit outline-4 :height 1.1))))
   `(org-level-3 ((t (,@headline :inherit outline-3 :height 1.25))))
   `(org-level-2 ((t (,@headline :inherit outline-2 :height 1.4))))
   `(org-level-1 ((t (,@headline :inherit outline-1 :height 1.60))))
   `(org-document-title ((t (,@headline ,:height 2.0 :underline nil))))))
#+end_src

New Bullets for Headers

#+begin_src emacs-lisp :tangle no
(setq org-superstar-headline-bullets-list '("⁖" "◉" "○" "✸" "✿"))
#+end_src

